Repository vecosystem/VECO_Frontend, pull requests merged in 2025-08, with the labels that each got.

#112 [FEAT] 목록 조회 API 구조
  src/apis/alarm/useDeleteAlarms.ts
  src/apis/alarm/useGetAlarmList.ts
  src/apis/alarm/usePatchAlarms.ts
  src/apis/external/useDeleteExternals.ts
  src/apis/external/useGetExternalList.ts
  src/apis/external/useGetGithubConnect.ts
  src/apis/goal/useDeleteGoals.ts
  src/apis/goal/useGetGoalList.ts
  src/apis/issue/useDeleteIssues.ts
  src/apis/issue/useGetIssueList.ts
  src/apis/setting/usePostWorkspaceTeam.ts
  src/components/ListView/ExternalItem.tsx
  src/components/ListView/GoalItem.tsx
  src/components/ListView/IssueItem.tsx
  src/components/ListView/ListViewToolbar.tsx
  src/constants/queryKey.ts
  src/pages/external/ExternalHome.tsx
  src/pages/goal/GoalHome.tsx
  src/pages/issue/IssueHome.tsx
  src/pages/notification/NotiHome.tsx
  src/pages/workspace/WorkspaceExternal.tsx
  src/pages/workspace/WorkspaceGoal.tsx
  src/pages/workspace/WorkspaceIssue.tsx
  src/types/alarm.ts
  src/types/common.ts
  src/types/detailitem.ts
  src/types/external.ts
  src/types/goal.ts
  src/types/issue.ts
  src/types/listItem.ts
  src/types/testDummy.tsx
  src/types/testNotiDummy.tsx
  src/utils/listItemUtils.tsx
Labels: ✨ FEAT, 🍀 선화

#117 [FEAT] 랜딩 페이지 연결, 설정 및 코드 관련 api 연결
  .gitignore
  package-lock.json
  package.json
  src/apis/external/useGetExternalName.ts
  src/apis/external/useGetSlackConnect.ts
  src/apis/goal/useGetGoalName.ts
  src/apis/issue/useGetIssueName.ts
  src/apis/setting/useGetWorkspaceTeams.ts
  src/apis/workspace/usePostCreateWorkspace.ts
  src/components/DetailView/DetailHeader.tsx
  src/constants/key.ts
  src/constants/queryKey.ts
  src/pages/external/ExternalDetail.tsx
  src/pages/external/components/ExternalToolModal.tsx
  src/pages/goal/GoalDetail.tsx
  src/pages/home/HomePage.tsx
  src/pages/issue/IssueDetail.tsx
  src/pages/setting/SettingMember.tsx
  src/pages/setting/SettingTeam.tsx
  src/pages/setting/components/MemberItem.tsx
  src/pages/setting/components/TeamItemSkeleton.tsx
  src/pages/setting/components/modal/MemberInviteModal.tsx
  src/pages/setting/components/modal/TeamCreateModal.tsx
  src/routes/PublicRoutes.tsx
  src/types/setting.ts
Labels: ✨ FEAT, 🍁 가을

#123 [FEAT] Workspace API 연동
  src/apis/workspace/usePostCreateWorkspace.ts
  src/components/Onboarding/WorkspaceNameInput.tsx
  src/constants/key.ts
  src/pages/onboarding/OnboardingCreateWorkspace.tsx
  src/pages/onboarding/OnboardingInviteMember.tsx
  src/types/workspace.ts
Labels: ✨ FEAT, 🌸 유민

#127 [FEAT] 생성될 목표, 이슈, 외부 이름 api 연동 완료
  package-lock.json
  package.json
  src/apis/external/useGetSlackConnect.ts
  src/apis/setting/useGetWorkspaceMembers.ts
  src/components/DetailView/DetailHeader.tsx
  src/components/DetailView/WorkspaceDetailHeader.tsx
  src/layouts/ProtectedLayout.tsx
  src/layouts/PublicLayout.tsx
  src/pages/Loading.tsx
  src/pages/Server500Error.tsx
  src/pages/external/components/ExternalToolModal.tsx
  src/pages/setting/SettingTeam.tsx
  src/pages/setting/components/TeamItemSkeleton.tsx
  src/pages/workspace/WorkspaceExternalDetail.tsx
  src/pages/workspace/WorkspaceGoalDetail.tsx
  src/pages/workspace/WorkspaceIssueDetail.tsx
Labels: ✨ FEAT, 🍁 가을

#129 [FIX] 사이드바 아이콘 오류 해결 및 라우팅 주소 변경 적용
  src/apis/setting/useGetWorkspaceProfile.ts
  src/components/Sidebar/DropdownHeader.tsx
  src/components/Sidebar/DropdownMenu.tsx
  src/components/Sidebar/FullSettingSidebarContent.tsx
  src/components/Sidebar/FullSidebarContent.tsx
  src/components/Sidebar/MiniSettingSidebarContent.tsx
  src/components/Sidebar/MiniSidebarContent.tsx
  src/components/Sidebar/SidebarItem.tsx
Labels: :rotating_light: FIX, 💎 진주

#135 [FIX] useLocalStorage 훅 수정
  src/hooks/useLocalStorage.ts
Labels: :rotating_light: FIX, 🌸 유민

#142 [FEAT] 사이드바 API 연동
  src/components/Sidebar/FullSettingSidebarContent.tsx
  src/components/Sidebar/FullSidebarContent.tsx
  src/components/Sidebar/MiniSettingSidebarContent.tsx
  src/components/Sidebar/MiniSidebarContent.tsx
  src/components/Sidebar/SettingSidebar.tsx
  src/components/Sidebar/Sidebar.tsx
Labels: ✨ FEAT, 💎 진주

#147 [FEAT] 세팅 프로필 API 연동 및 사이드바 토글상태 로컬 스토리지 저장
  src/apis/auth.ts
  src/apis/setting/useDeleteMyProfileImage.ts
  src/apis/setting/usePatchMyProfileImage.ts
  src/components/Sidebar/DropdownHeader.tsx
  src/components/Sidebar/DropdownMenu.tsx
  src/components/Sidebar/FullSettingSidebarContent.tsx
  src/components/Sidebar/FullSidebarContent.tsx
  src/components/Sidebar/MiniSettingSidebarContent.tsx
  src/components/Sidebar/MiniSidebarContent.tsx
  src/components/Sidebar/SettingSidebar.tsx
  src/components/Sidebar/Sidebar.tsx
  src/pages/setting/SettingMyProfile.tsx
  src/pages/setting/SettingWorkspaceProfile.tsx
  src/stores/ui.ts
  src/stores/useSidebarStore.ts
Labels: ✨ FEAT, 💎 진주

#146 [FIX] 깃허브, 슬랙 리다이렉트 설정
  src/apis/external/useGetExternalLinks.ts
  src/apis/external/useGetExternalSimplelssue.ts
  src/apis/external/useGetGithubConnect.ts
  src/apis/external/useGetGithubInstallationId.ts
  src/apis/external/useGetGithubRepository.ts
  src/apis/external/useGetSlackConnect.ts
  src/constants/queryKey.ts
  src/pages/external/ExternalDetail.tsx
  src/pages/external/ExternalHome.tsx
  src/pages/external/GithubComplete.tsx
  src/pages/external/SlackComplete.tsx
  src/pages/external/components/ExternalToolArea.tsx
  src/pages/setting/SettingMember.tsx
  src/pages/setting/SettingTeam.tsx
  src/pages/workspace/WorkspaceExternal.tsx
  src/pages/workspace/WorkspaceExternalDetail.tsx
  src/routes/ProtectedRoutes.tsx
Labels: :rotating_light: FIX, 🍁 가을

#155 [FEAT] 로그인 완료 시 리다이렉트 기능 구현
  src/pages/workspace/WorkspaceComplete.tsx
Labels: ✨ FEAT, 🍁 가을

#159 [FEAT] 액세스 토큰에 따른 protected layout 막기
  src/layouts/ProtectedLayout.tsx
Labels: :rotating_light: FIX, 🍁 가을

#169 [FIX] 스크롤 전파 문제 해결 및 회원탈퇴 API 연동
  src/apis/auth.ts
  src/components/Sidebar/SettingSidebar.tsx
  src/components/Sidebar/Sidebar.tsx
  src/constants/sidebar.ts
  src/layouts/ProtectedLayout.tsx
  src/pages/setting/components/modal/WithdrawModal.tsx
Labels: ✨ FEAT, :rotating_light: FIX, 💎 진주

#167 [FEAT] 온보딩 절차 경로 강제 접근 제어 & 사용자 입력 정보 유지 기능 구현
  src/components/AuthRedirect.tsx
  src/components/Onboarding/OnboardingGuard.tsx
  src/components/Onboarding/SocialLoginButton.tsx
  src/components/Onboarding/WorkspaceNameInput.tsx
  src/hooks/useOnboardingGuard.ts
  src/index.css
  src/pages/onboarding/InviteLoading.tsx
  src/pages/onboarding/OnboardingCreateWorkspace.tsx
  src/pages/onboarding/OnboardingFinish.tsx
  src/pages/onboarding/OnboardingInviteMember.tsx
  src/pages/onboarding/OnboardingSSOLogin.tsx
  src/routes/PublicRoutes.tsx
  src/stores/onboardingStatus.ts
  src/stores/onboardingWorkspace.ts
  src/utils/validateInviteUrl.tsx
  src/utils/validateWorkspaceName.ts
Labels: ✨ FEAT, :rotating_light: FIX, :recycle: REFACTOR, 🌸 유민

#170 [FEAT] 목표 작성 API 연동
  src/apis/external/useGetExternalName.ts
  src/apis/goal/useGetGoalName.ts
  src/apis/goal/useGetSimpleGoalList.ts.ts
  src/apis/goal/usePostCreateGoalDetail.ts
  src/apis/issue/useGetIssueName.ts
  src/apis/issue/useGetSimpleIssueList.ts
  src/components/DetailView/CompletionButton.tsx
  src/components/DetailView/MultiSelectPropertyItem.tsx
  src/components/DetailView/PropertyItem.tsx
  src/components/DetailView/TextEditor/DetailTextEditor.tsx
  src/components/DetailView/TextEditor/lexical-plugins/EnterAsParagraphPlugin.tsx
  src/components/DetailView/TextEditor/lexical-plugins/LoadFromJsonPlugin.tsx
  src/components/DetailView/TextEditor/lexical-plugins/SubmitHandlePlugin.tsx
  src/components/Dropdown/ArrowDropdown.tsx
  src/components/Dropdown/MultiSelectDropdown.tsx
  src/constants/mutationKey.ts
  src/constants/queryKey.ts
  src/hooks/useToggleMode.ts
  src/pages/external/ExternalDetail.tsx
  src/pages/goal/GoalDetail.tsx
  src/pages/issue/IssueDetail.tsx
  src/pages/workspace/WorkspaceExternalDetail.tsx
  src/pages/workspace/WorkspaceGoalDetail.tsx
  src/pages/workspace/WorkspaceIssueDetail.tsx
  src/types/detailitem.ts
  src/types/goal.ts
  src/utils/editorStateIO.ts
  src/utils/formatDate.ts
Labels: ✨ FEAT, 🐥 주원

#178 [FEAT] 팀원 초대하기 API 연동
  src/apis/setting/useGetInviteMembers.ts
  src/constants/queryKey.ts
  src/pages/setting/SettingMember.tsx
  src/pages/setting/components/modal/MemberInviteModal.tsx
  src/types/setting.ts
Labels: ✨ FEAT, 🌸 유민

#179 [FIX] 초기 로딩 시 처리
  src/pages/external/ExternalHome.tsx
  src/pages/goal/GoalHome.tsx
  src/pages/issue/IssueHome.tsx
  src/pages/notification/NotiHome.tsx
  src/pages/workspace/WorkspaceExternal.tsx
  src/pages/workspace/WorkspaceGoal.tsx
  src/pages/workspace/WorkspaceIssue.tsx
Labels: ✨ FEAT, 🍀 선화

#187 [FEAT] 사이드바 UX 개선
  src/components/Sidebar/FullSidebarContent.tsx
  src/components/Sidebar/SidebarItem.tsx
  src/hooks/useAutoCloseSidebar.ts
  src/layouts/ProtectedLayout.tsx
  src/pages/setting/SettingWorkspaceProfile.tsx
  src/stores/ui.ts
Labels: ✨ FEAT, 💎 진주

#195 [REFACTOR] 상세페이지 하단 토스트 & 작성 중지 경고 모달 추가
  src/App.tsx
  src/components/DetailView/DetailTitle.tsx
  src/components/Toast/ToastProvider.tsx
  src/components/Toast/ToastViewport.tsx
  src/pages/external/ExternalDetail.tsx
  src/pages/goal/GoalDetail.tsx
  src/pages/issue/IssueDetail.tsx
  src/pages/workspace/WorkspaceExternalDetail.tsx
  src/pages/workspace/WorkspaceGoalDetail.tsx
  src/pages/workspace/WorkspaceIssueDetail.tsx
Labels: :recycle: REFACTOR, :art: UI, 🐥 주원

#197 [REFACTOR] 상세페이지 반응형 수정
  src/pages/external/ExternalDetail.tsx
  src/pages/goal/GoalDetail.tsx
  src/pages/issue/IssueDetail.tsx
  src/pages/workspace/WorkspaceExternalDetail.tsx
  src/pages/workspace/WorkspaceGoalDetail.tsx
  src/pages/workspace/WorkspaceIssueDetail.tsx
Labels: :recycle: REFACTOR, 🐥 주원

#201 [FIX] 상세페이지 속성 탭 오류 수정
  src/pages/external/ExternalDetail.tsx
  src/pages/goal/GoalDetail.tsx
  src/pages/issue/IssueDetail.tsx
  src/pages/workspace/WorkspaceExternalDetail.tsx
  src/pages/workspace/WorkspaceGoalDetail.tsx
  src/pages/workspace/WorkspaceIssueDetail.tsx
Labels: :rotating_light: FIX, 🐥 주원

#211 [DOCS] 칸반 정리 및 백호 README.md에 일부 내용 추가
  README.md
Labels: :page_facing_up: DOCS, 🐥 주원
