Repository vecosystem/VECO_Frontend, pull requests merged in 2025-07, with the labels that each got.

#6 [SETTING] index.css 공통 작업
  index.html
  src/index.css
Labels: 🍀 선화, ⚙️ SETTING

#11 [ADD] vite-plugin-svgr 세팅
  package-lock.json
  package.json
  src/assets/icons/bell.svg
  src/assets/icons/document.svg
  src/assets/icons/dropdown.svg
  src/assets/icons/external.svg
  src/assets/icons/goal.svg
  src/assets/icons/issue.svg
  src/assets/icons/plus.svg
  src/vite-env.d.ts
  svg.d.ts
  tsconfig.json
  vite.config.ts
Labels: 💎 진주, ➕ ADD

#16 [ADD] 공통 아이콘 추가
  src/assets/icons/bell.svg
  src/assets/icons/document.svg
  src/assets/icons/dropdown.svg
  src/assets/icons/external.svg
  src/assets/icons/goal.svg
  src/assets/icons/gray.svg
  src/assets/icons/issue.svg
  src/assets/icons/plus.svg
Labels: 💎 진주, ➕ ADD

#19 [SETTING] index.css 공통 작업 폰트 수정
  index.html
  src/assets/fonts/SpoqaHanSansNeo-Bold.woff2
  src/assets/fonts/SpoqaHanSansNeo-Regular.woff2
  src/index.css
Labels: 🍀 선화, ⚙️ SETTING

#18 [UI] ListView Item 컴포넌트 생성
  src/assets/icons/date.svg
  src/assets/icons/pr-0.svg
  src/assets/icons/pr-1.svg
  src/assets/icons/pr-2.svg
  src/assets/icons/pr-3.svg
  src/assets/icons/pr-4.svg
  src/assets/icons/trash.svg
  src/components/ListView/GoalItem.tsx
  src/components/ListView/IssueItem.tsx
  src/types/listItem.ts
  src/utils/listItemUtils.tsx
Labels: :art: UI, 🍀 선화

#14 [UI] 사이드바 아이템 컴포넌트 및 드롭다운 기능 구현
  package-lock.json
  package.json
  src/components/Sidebar/DropdownHeader.tsx
  src/components/Sidebar/DropdownMenu.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SidebarItem.tsx
  src/layouts/ProtectedLayout.tsx
  src/routes/ProtectedRoutes.tsx
  tsconfig.json
Labels: :art: UI, 💎 진주

#24 [UI] OnboardingCreateWorkspace 페이지 UI 작업
  src/components/Onboarding/PageIndicator.tsx
  src/constants/onboardingSteps.ts
  src/pages/OnboardingCreateWorkspace.tsx
Labels: :art: UI, 🌸 유민

#28 [UI] 모달 컴포넌트 구현
  package-lock.json
  package.json
  src/components/Modal/Modal.tsx
  src/hooks/useModal.ts
Labels: :art: UI, 🍁 가을

#27 [FEAT] 사이드바 라우팅 연결 및 Outlet 자식 레이아웃 구조 개선
  src/components/Sidebar/Sidebar.tsx
  src/layouts/ProtectedLayout.tsx
  src/routes/ProtectedRoutes.tsx
Labels: ✨ FEAT, 💎 진주

#30 [UI] OnboardingSSOLogin 페이지 UI 수정
  src/pages/OnboardingSSOLogin.tsx
Labels: :recycle: REFACTOR, :art: UI, 🌸 유민

#36 [UI] 목표 기본화면 페이지
  public/vecosmall.svg
  src/assets/icons/box.svg
  src/assets/icons/check-box-o.svg
  src/assets/icons/check-box-x.svg
  src/assets/icons/date.svg
  src/assets/icons/filter.svg
  src/assets/icons/list.svg
  src/assets/icons/trash-black.svg
  src/components/ListView/GoalItem.tsx
  src/components/ListView/GroupTypeIcon.tsx
  src/components/ListView/IssueItem.tsx
  src/components/ListView/SelectAllCheckbox.tsx
  src/components/ListView/TeamIcon.tsx
  src/layouts/ProtectedLayout.tsx
  src/pages/goal/GoalHome.tsx
  src/routes/ProtectedRoutes.tsx
  src/types/listItem.ts
  src/utils/listItemUtils.tsx
Labels: :art: UI, 🍀 선화

#41 [UI] 변경 아이콘 적용한 사이드바 전체 UI 구현 및 스크롤바 커스텀
  src/assets/icons/bell.svg
  src/assets/icons/document.svg
  src/assets/icons/external.svg
  src/assets/icons/goal.svg
  src/assets/icons/issue.svg
  src/assets/icons/setting.svg
  src/assets/logos/veco-circle-logo-bg-navy.svg
  src/assets/logos/veco-circle-logo-bg-white.svg
  src/components/Sidebar/DropdownHeader.tsx
  src/components/Sidebar/DropdownMenu.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SidebarItem.tsx
  src/index.css
Labels: :art: UI, 💎 진주

#46 [UI] Error404NotFound 페이지 UI 작업
  src/pages/onboarding/Error404NotFound.tsx
  src/pages/onboarding/OnboardingCreateWorkspace.tsx
  src/pages/onboarding/OnboardingFinish.tsx
  src/pages/onboarding/OnboardingInviteMembers.tsx
  src/pages/onboarding/OnboardingSSOLogin.tsx
  src/routes/PublicRoutes.tsx
Labels: :art: UI, 🌸 유민

#62 [REFACTOR] 온보딩 페이지 전체 리팩토링
  src/assets/icons/whitecheck.svg
  src/components/Onboarding/InviteCodeInput.tsx
  src/components/Onboarding/PrimaryButton.tsx
  src/components/Onboarding/SocialLoginButton.tsx
  src/components/Onboarding/WorkspaceNameInput.tsx
  src/layouts/PublicLayout.tsx
  src/pages/Error404NotFound.tsx
  src/pages/onboarding/OnboardingCreateWorkspace.tsx
  src/pages/onboarding/OnboardingFinish.tsx
  src/pages/onboarding/OnboardingInviteMember.tsx
  src/pages/onboarding/OnboardingSSOLogin.tsx
  src/pages/onboarding/ParticipateWorkspaceInputPw.tsx
  src/routes/ProtectedRoutes.tsx
  src/routes/PublicRoutes.tsx
  src/routes/index.tsx
  src/utils/validateWorkspaceName.ts
Labels: :recycle: REFACTOR, 🌸 유민

#53 [UI] Setting_Team 페이지 구현
  package-lock.json
  package.json
  src/assets/icons/user-round-search.svg
  src/assets/icons/white-check.svg
  src/assets/icons/x.svg
  src/constants/regex.ts
  src/layouts/ProtectedLayout.tsx
  src/pages/goal/GoalHome.tsx
  src/pages/issue/IssueHome.tsx
  src/pages/setting/SettingMember.tsx
  src/pages/setting/SettingTeam.tsx
  src/pages/setting/components/MemberCheckbox.tsx
  src/pages/setting/components/MemberItem.tsx
  src/pages/setting/components/ProfileImage.tsx
  src/pages/setting/components/SubProfileImage.tsx
  src/pages/setting/components/TeamHeader.tsx
  src/pages/setting/components/TeamItem.tsx
  src/pages/setting/components/modal/MemberInviteModal.tsx
  src/pages/setting/components/modal/ModalButton.tsx
  src/pages/setting/components/modal/TeamCreateModal.tsx
  src/routes/ProtectedRoutes.tsx
Labels: :art: UI, 🍁 가을

#65 [UI] 설정 사이드바 UI 구현
  src/assets/icons/left-arrow.svg
  src/assets/icons/table-hover.svg
  src/assets/icons/user-profile-hover.svg
  src/assets/icons/user-profile.svg
  src/assets/icons/users-hover.svg
  src/assets/icons/users.svg
  src/components/Sidebar/SettingSidebar.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SidebarItem.tsx
  src/layouts/ProtectedLayout.tsx
Labels: :art: UI, 💎 진주

#72 [UI] 설정 나의 프로필 페이지 구현
  src/assets/icons/check-box-o-red.svg
  src/assets/icons/pencil.svg
  src/assets/icons/table.svg
  src/assets/icons/user-circle.svg
  src/components/Dropdown/SettingDropdown.tsx
  src/components/Sidebar/SettingSidebar.tsx
  src/index.css
  src/pages/setting/SettingMyProfile.tsx
  src/pages/setting/components/modal/WithdrawModal.tsx
  src/routes/ProtectedRoutes.tsx
Labels: :art: UI, 💎 진주

#74 [FEAT] 온보딩 가드 훅 구현 및 UI 반응형 개선
  src/components/Onboarding/PageIndicator.tsx
  src/constants/onboardingSteps.ts
  src/hooks/useOnboardingGuard.ts
  src/layouts/PublicLayout.tsx
  src/pages/onboarding/OnboardingCreateWorkspace.tsx
  src/pages/onboarding/OnboardingFinish.tsx
  src/pages/onboarding/OnboardingInviteMember.tsx
  src/pages/onboarding/OnboardingSSOLogin.tsx
Labels: ✨ FEAT, :recycle: REFACTOR, 🌸 유민

#77 [UI] 워크스페이스 전체 팀 기본 페이지
  src/components/ListView/GroupTypeIcon.tsx
  src/components/ListView/WorkspaceIcon.tsx
  src/pages/workspace/WorkspaceExternal.tsx
  src/pages/workspace/WorkspaceGoal.tsx
  src/pages/workspace/WorkspaceIssue.tsx
  src/routes/ProtectedRoutes.tsx
Labels: :art: UI, 🍀 선화

#78 [REFACTOR] 모달 리팩토링
  src/components/Modal/Modal.tsx
  src/index.css
Labels: :recycle: REFACTOR, 🍁 가을

#82 [UI] DetailView Item 컴포넌트 생성
  src/assets/icons/check-sm.svg
  src/assets/icons/date-lg.svg
  src/assets/icons/pr-1-sm.svg
  src/assets/icons/pr-2-sm.svg
  src/assets/icons/pr-3-sm.svg
  src/assets/icons/pr-4-sm.svg
  src/assets/icons/status/doing.svg
  src/assets/icons/status/done.svg
  src/assets/icons/status/none.svg
  src/assets/icons/status/review.svg
  src/assets/icons/status/todo.svg
  src/assets/icons/user-circle-sm.svg
  src/assets/icons/write.svg
  src/components/DetailView/CompletionButton.tsx
  src/components/DetailView/DetailHeader.tsx
  src/components/DetailView/DetailTextEditor.tsx
  src/components/DetailView/DetailTitle.tsx
  src/components/DetailView/PropertyItem.tsx
  src/pages/goal/GoalDetail.tsx
  src/routes/ProtectedRoutes.tsx
  src/types/detailitem.ts
Labels: :art: UI, 🐥 주원

#93 [UI] 상세페이지 댓글창 컴포넌트 구현
  src/assets/icons/gray-lg.svg
  src/assets/icons/status/doing.svg
  src/assets/icons/status/done.svg
  src/assets/icons/status/none.svg
  src/assets/icons/status/review.svg
  src/assets/icons/status/todo.svg
  src/components/DetailView/Comment/CommentCompletionButton.tsx
  src/components/DetailView/Comment/CommentInput.tsx
  src/components/DetailView/Comment/CommentItem.tsx
  src/components/DetailView/Comment/CommentSection.tsx
  src/components/DetailView/CompletionButton.tsx
  src/components/DetailView/DetailTitle.tsx
  src/components/DetailView/PropertyItem.tsx
  src/pages/goal/GoalDetail.tsx
Labels: ✨ FEAT, :art: UI, 🐥 주원

#90 [FEAT] 설정 팀 api 연결
  package-lock.json
  package.json
  src/App.tsx
  src/apis/setting/useGetWorkspaceMembers.ts
  src/apis/setting/useGetWorkspaceTeams.ts
  src/apis/setting/usePostWorkspaceTeam.ts
  src/constants/queryKey.ts
  src/types/setting.ts
  src/utils/queryClient.ts
  src/vite-env.d.ts
Labels: ✨ FEAT, 🍁 가을

#97 [FEAT] 깃허브 api 세팅 및 워크스페이스 경로 수정
  src/apis/external/useGetGithubConnect.ts
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SortableDropDownList.tsx
  src/components/Sidebar/SortableDropdown.tsx
  src/constants/queryKey.ts
  src/pages/external/components/ExternalToolModal.tsx
  src/pages/setting/components/MemberItem.tsx
  src/pages/setting/components/ProfileImage.tsx
  src/pages/setting/components/SubProfileImage.tsx
  src/pages/setting/components/TeamHeader.tsx
  src/pages/setting/components/TeamItem.tsx
  src/routes/ProtectedRoutes.tsx
Labels: ✨ FEAT, 🍁 가을
